version: 2.1

executors: &executors
  node:
    docker:
      - image: circleci/node:12.12.0-stretch

commands: &commands
  cache_yarn:
    parameters:
      cache_version:
        type: string
        default: v1
    steps:
      - restore_cache:
          keys:
          - npm-cache-{{ checksum "./yarn.lock" }}-<< parameters.cache_version >>-
          - npm-cache-{{ checksum "./yarn.lock" }}-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
          - ~/.cache/yarn
          key: npm-cache-{{ checksum "./yarn.lock" }}-<< parameters.cache_version >>-

orbs:
  node:
    commands: *commands
    executors: *executors
    jobs:
      build:
        working_directory: ~/firebase-google-account-switcher
        executor: node
        steps:
          - checkout
          - cache_yarn
          - run: yarn build
          - run: yarn eslint src/js --ext .ts
          - run: yarn stylelint src/css
      test:
        working_directory: ~/firebase-google-account-switcher
        executor: node
        steps:
          - checkout
          - cache_yarn
          - run: yarn test
      package:
        working_directory: ~/firebase-google-account-switcher
        executor: node
        steps:
          - checkout
          - cache_yarn
          - run: yarn package
          - store_artifacts:
              path: extension.zip

workflows:
  version: 2
  on_commit:
    jobs:
      - node/build
      - node/test
  on_release:
    jobs:
      - node/package:
          filters:
            branches:
              only: /master/
